### ISSUE TITLE
Feature Request: Source Map Support for Error Reporting and Debugging

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode-test-cli#11]
Currently Test Runs do not map exceptions back to the original source:
```
  test
    1) first test
  0 passing (46ms)
  1 failing
1 test failed.
  1) test
       first test:
     Error: oops
        at C:\Users\JGrote\Projects\vscode-pester\dist\test.js:1:81
        at Context.<anonymous> (C:\Users\JGrote\Projects\vscode-pester\dist\test.js:1:99)
        at process.processImmediate (node:internal/timers:476:21)
```

And this is also true of breakpoints. I would assume this is because the "inner" runner is the vscode electron which does not accept most node environment variables that enable this behavior and so it must be done in the entrypoint runner code.

In the Pester custom mocha test runner we injected swc-node for the transpilation process so our mocha test runner could be written in TS and that has source map support, something similar either natively or provided in the docs as guidance would be very helpful and would foster greater adoption of this test runner for extension development.

```js
/* eslint-disable @typescript-eslint/no-var-requires */
// This shim is needed because you cannot inject the transpiler via NODE_OPTIONS into a packaged electron app like

// code.exe and vscode-test starts the test runner as a packaged app
exports.run = async () => {
	// This allows us to dynamically load typescript files without first compiling them with tsc/esbuild
	require('@swc-node/register')

	// eslint-disable-next-line @typescript-eslint/no-var-requires
	return require('./runTestsInner.ts').run()
}
```

**Comment by connor4312** [comment]
I don't plan to do this inside the test CLI, as the CLI doesn't know anything about sourcemaps. We could do it in the runner extension though when we show output.

Note that for adding loaders and such there is the `mocha.require` option.
