### ISSUE TITLE
Cannot specify a custom Mocha reporter

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/vscode-test-cli#55]
While the option exists to specify a custom reporter (via mocha.reporter), that doesn't work in practice because of the structuredClone on the config object.

If you try, you'll get an error like
```
DataCloneError: class JunitSpecReporter extends mocha.reporters.Base {
    junitReporter;
    specReporter;
    constructor(run...<omitted>...
} could not be cloned.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at DesktopPlatform.prepare (file:///C:/__w/1/s/node_modules/@vscode/test-cli/out/cli/platform/desktop.mjs:18:22)
    at file:///C:/__w/1/s/node_modules/@vscode/test-cli/out/bin.mjs:53:38
    at Array.map (<anonymous>)
    at prepareConfigs (file:///C:/__w/1/s/node_modules/@vscode/test-cli/out/bin.mjs:51:48)
    at runConfigs (file:///C:/__w/1/s/node_modules/@vscode/test-cli/out/bin.mjs:128:28)
    at main (file:///C:/__w/1/s/node_modules/@vscode/test-cli/out/bin.mjs:34:26)
```

**Comment by connor4312** [comment]
You will need to pass the path to a reporter, not a reporter object, as tests are run in the extension host and not the CLI

**Comment by 50Wliu** [comment]
Oh, awesome! Could this be documented? The typings had me believing otherwise (plus, this worked with the old index + runTest approach).
![image](https://github.com/user-attachments/assets/b5d63691-30f7-4152-99f4-b7ea02aec86f)

**Comment by connor4312** [comment]
Ah, yea, I can try and narrow them a bit
